### ISSUE TITLE
Elegant async code with ES6 Promises

### ISSUE THREAD

**Issue by davidjgoss** [mkjs/talks#10]
Promises are by no means new to JavaScript, but their standardisation as part of ES2015 has changed them from a handy library feature to a core tool with which we can write elegant code for async functionality.

The talk will cover:
- A whistle-stop tour of Promises for the uninitiated
- Neatly chaining functionality together with `.then()`
- Smartly handling errors with `.catch()`
- A glimpse into the future with `async`/`await`

This is all viewed through the lens of building  a "real" (albeit rather contrived) page.

**Comment by ghost** [comment]
@davidjgoss this sounds great, I know that some people were eager to hear some ES6 talks.

Do you know when you might like to give the talk? Dates so far are 23rd Feb and 29th Mar. Further ahead I aim to make the meetups for the last Tuesday in a month.

**Comment by davidjgoss** [comment]
@jrcoward Let's say 23rd Feb if you have a gap there

**Comment by ghost** [comment]
@davidjgoss yeah that works really well!

**Comment by ghost** [comment]
@davidjgoss I'll stick it up on the meetup page for that event in the next few days
