### ISSUE TITLE
Error handling with Raygun.io

### ISSUE THREAD

**Issue by karlgjertsen** [mkjs/talks#11]
We don't like to admit it, but our applications have errors. Some of these are our fault, some are due to bad configuration or a problem with the host environment. But what if we were notified about these errors as they happen? What if we could fix the problem before the user told us about it? RayGun provides us with the tools to do this. From installation to configuration and beyond, I'll show you how you can use RayGun in your applications. 

(I also have some Raygun t-shirts to give away!)

**Comment by ghost** [comment]
@kgjertsen  - Sorry I haven't gotten back to you sooner, I must not be subscribed to the repo or something.

I have seen raygun.io mentioned in some blog posts etc., it would be great to have someone explaining how to use it. Do you have an idea when you would like to do the talk? The meetups are usually the last Tuesday of the month, the next event is 29th March.

(Everyone loves free t-shirts!)

**Comment by karlgjertsen** [comment]
I'll check dates and get back to you, but I think that date will be ok.
Karl

**Comment by ghost** [comment]
Great! :+1:

**Comment by karlgjertsen** [comment]
Hi,
Sorry for the delay in getting back to you, but I have been trying to rearrange a few things in my diary. I will confirm tomorrow.
Karl

**Comment by ghost** [comment]
Hi @karlgjertsen ,

No worries! Thanks for keeping me up to date.

James

**Comment by karlgjertsen** [comment]
Really sorry...I have had a hectic week.
I have checked my diary and I can do the 29th March. If this has gone, sign me up for the next event.

Regards,
Karl

**Comment by ghost** [comment]
Hi @karlgjertsen 

No worries!

29 March is still available, I'll put you down for it.

I'll get in touch a bit closer to the date to let you know how to get to the venue etc.

Regards,

James

**Comment by karlgjertsen** [comment]
Thank you.

What have the number of attendees been recently?

Karl

On 8 Mar 2016, at 08:51, jrcoward <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @karlgjertsenhttps://github.com/karlgjertsen

No worries!

29 March is still available, I'll put you down for it.

I'll get in touch a bit closer to the date to let you know how to get to the venue etc.

Regards,

James

**Comment by ghost** [comment]
There have been about 25 attendees at the last two events.

James

**Comment by karlgjertsen** [comment]
If there's anything I can do to increase the number, let me know.

I can give away t-shirts and if you can get 50 people, I can arrange to cover the costs of food and drink.

Is it ok for me to send an email to the group mailing list?

Regards,

Karl

On 8 Mar 2016, at 08:58, jrcoward <notifications@github.com<mailto:notifications@github.com>> wrote:

There have been about 25 attendees at the last two events.

James

**Comment by ghost** [comment]
If you can promote the event via twitter or whatever, that would be great.
I'm going to be promoting the event at a different tech event this week, so we may see some extra attendance as a result of that.

I'll mention the t-shirts in the event on meetup, maybe that will get a few more people to come :grin: 

Would you mind sending the text of the email to me first? You can DM it to me on twitter, or you can send it to the MK.js email hello@mkjs.org

**Comment by karlgjertsen** [comment]
Hi,

I will be tweeting about it and Raygun will retweet it too.

Which other events do you go to? I’m always looking for new tech groups to join. ;-)

How about I send you an email and you can forward it to the group?

Speak soon,

Karl

**Comment by ghost** [comment]
Hi Karl,

That's great, I'm sure you both have  a bit more reach than I do!

I've attended:
- DevOps:MK
- Agile:MK
- IoT:MK  (Internet of Things)
- BigData|MK

They have all been good. There is also a Java/JVM User Group and a .NET meetup starting in the area which I'm sure will be good.

They all have presence on meetup so shouldn't be too difficult to find.

Sure I can do that, you can send it to the hello@mkjs.org .

Regards,

James
