### ISSUE TITLE
The balance between confident code and learning

### ISSUE THREAD

**Issue by inspiraller** [mkjs/talks#13]
Javascript is the quickest programming language to see results. It doesn't need compiling. It is immediately accessible for anyone who doesn't code to start learning. Over the last 6 years it has gone through a massive transition with the push of mvc frameworks, isomorphic development with npm, and more oo like features of es6 to es7. 

Before this we have seen libraries and tools like prototype, dojo, jquery, npm, bootstrap gradually empower programmers to apply themselves without having to learn the divide from backend to ajax, behaviour to front end design to get work. 

We have also seen more younger developers join the stack to contribute as they are born into an age of smart phones and internet available as they learn to crawl.

Unfortunately, many of these tools have lead to a poor understanding of the basics. Some have restricted our flow and not really sped up or given us any more pleasure or confidence in coding.

Now, more than ever we need an edge, to afford to stay in the game. More competition, more developers in the game, more skills required, more tools than ever before make it both easy to develop, but harder to get hired because its impossible to know everything and every developer has a niche.

On top of all that you can safely say that the future of our trusted tools is bleak given the evolution of trends from a yui utility to underscore or lodash to a framework again. 

So what are we todo? How do we stay in the game?
1) master css
2) master html
3) master browsers, performance, latency
4) master dom manipulation, 
5) master seo, jsonld, micro formats
6) master estimating
7) master managing a team and organising code to facilitate confidence
8) master version control management
9) .... The list goes on now because you have to learn the popular tools from npm, react, redux, es6 and so forth. 

So how do you manage your learning while simultaneously developing code with confidence that you can keep going back to, share with with others and work quickly without creating too much technical debt?

This is open to debate?

**Comment by jamescoward** [comment]
Hi @inspiraller, sorry it took me so long to get to this!
I didn't get a notification and I haven't really been keeping on top of it very well.

It sounds like an interesting talk about the balancing act we have as developers, are you still interested in giving the talk?

**Comment by inspiraller** [comment]
Hi. Yes I'd be interested although this is more of a collaboration, audience participation to contribute to finding the ideal approach. What is the expected routine of the talker? How long is each talk?

**Comment by jamescoward** [comment]
I think it is an interesting idea, a break from having someone stand at the front and talk about something.

The usual format is someone has a presentation and talks for ~20 minutes, although shorter or longer talks are welcome as well.

What were you thinking the ideal structure of this would be?

**Comment by inspiraller** [comment]
If you don't have one i'd bring a projector and laptop. Introduce myself,
my experience, where i've worked and what i do. Then get everyone to spend
5 mins reading the subject material which you have already read and ask
around what others thoughts are. If there is a whiteboard ill use that, if
not type out the feedback. Then in the time left summarise and share with
the group.

**Comment by jamescoward** [comment]
We have a projector with HDMI and VGA, so if you bring your laptop along that'll work nicely.

Do you have any idea when you would like to give the talk/discussion? We usually have the meetup's on a Tuesday towards the end of the month. Would you be ready for October, perhaps the 25th? or would you prefer later?

**Comment by inspiraller** [comment]
Yes that date works for me.

**Comment by jamescoward** [comment]
OK great, I will schedule your talk for 25th Oct.

I'll create the meetup event over the weekend. 

Would you mind writing a short blurb just to say what the talk will be about? Just a couple of line I can put on the event page.

Do you have a twitter or something you'd like me to link to from the event page?

Will you need:
Internet
Sound
Anything else other than a projector?

**Comment by inspiraller** [comment]
How about this:

_The balance between confident code and learning_

The evolution of javascript and supporting technologies seem to be
advancing at an exponential rate.
Now, more than ever we need an edge, to afford to stay in the game.
More competition, more developers in the game, more skills required, more
tools than ever before make it both easy to develop, but harder to get
hired because its impossible to know everything and every developer has a
niche.
- Are your existing skills rapidly going out of date?
- Are you losing confidence in what you have just built because now x
  framework has gained traction?
- Have you used a new technology and found yourself struggling with
  idiosyncracies that outweigh the benefit of using it in the first place.
- Are you struggling because your boss or team just making all the
  decisions and leaving you to submissively absorb the time and effort
  delivering poor quality or not meeting targets?

This talk is to open up awareness and question all of us, to open debate
and help us find the right skills to adopt and balance of time we invest
between learning and application to stay in the game of javascript related
work.

**Comment by inspiraller** [comment]
drop the bullets if it's too much for a short blurb:

_The balance between confident code and learning_

The evolution of javascript and supporting technologies seem to be
advancing at an exponential rate.
Now, more than ever we need an edge, to afford to stay in the game: More
competition, more developers in the game, more skills required, more tools
than ever before make it both easy to develop, but harder to get hired or
compete because its impossible to know everything and every developer has a
niche.
This talk is to open up awareness and question all of us, to open debate
and help us find the right skills to adopt and balance of time we invest
between learning and application to stay in the game of javascript related
work.

**Comment by jamescoward** [comment]
I think its great with the bullets, thanks for that. I'll send you a link once the event page is up

**Comment by jamescoward** [comment]
Hi @inspiraller,

meetup is up at https://www.meetup.com/mkjscript/events/234568371/

**Comment by jamescoward** [comment]
Do you have something you'd like me to link to for who is doing the talk?

**Comment by inspiraller** [comment]
Brilliant. Thanks. Not at the moment.

**Comment by jamescoward** [comment]
Ok great 😄

**Comment by jamescoward** [comment]
Hey @inspiraller ,

Just wanted to check, are you going to need internet on Tuesday?

I'll be arriving at the venue at around 6.45, I'll send you a message on meetup with my number incase you need to reach me.

**Comment by inspiraller** [comment]
hi
Not necessarily. but would be useful.
cheers
steve

**Comment by inspiraller** [comment]
Feedback from talk:

David:
    don't panic

Jason:
    goto events once a month?
    live streaming of events.

Dan:
  over estimating to allow for learning..
  multiplied

  legacy technical debt.

Anonymous:
  be clear of pressures
  Recruiters aren't necessarily clear about what they want.

James:
  potentially 90% aren't working with latest frameworks or techstack..

Rob:
  oocss and bem - harry roberts.
  organisation, componentize, modularise

John:
  smaccs
  o

Anonymous:
  Learn important design patterns.

Out of all attendees who has used the following commercially?:
  Angular:3
  React: 3
  Angular2: none
  Polymer: 
  jquery: 9
  vanila js: 9
  backbone: 2
  node: 4
  server side development: 12
  linting, coding standards, test: 5
    enzyme: 
      interactive testing
      (3 people - end to end testing - might as well expect 50% error,)

  data management: 5 people

Out of all attendees who uses the following about 80% of their time:

  javascript: 8

  front end devs: 7

How much time should i spend learning:
  25 mins? timer apps. non - rigid.

**Comment by jamescoward** [comment]
Thanks @inspiraller

**Comment by jamescoward** [comment]
@inspiraller made a repo here: https://github.com/mkjs/feedback-from-confident-code/blob/master/README.md for the feedback. Feel free to make PRs if you want to add anything else.
