### ISSUE TITLE
Talk about Yeoman

### ISSUE THREAD

**Issue by PureRandom** [mkjs/talks#14]
Talking about the Scaffolding tool Yeoman. This is a very useful tool to set up a default project. I think this is a great tool to demo and also show how you can make your own to make public or for internal.  

More detail about Yeoman is here [yeoman.io](http://yeoman.io/)

**Comment by jamescoward** [comment]
Hi @PureRandom ,

This sounds great, yeoman is something I have been meaning to investigate.

Do you have an idea of when you would like to give the talk? We usually have meetups on a Tuesday towards the end of the month. Would October work for you, or would you prefer later?

**Comment by PureRandom** [comment]
Sorry for the delay in getting back to you. October wouldn't be best as I have a busy week then, but November would be OK if we want to do it last week Tuesday then?

Thanks,

**Comment by jamescoward** [comment]
Hi @PureRandom , no problem!
November would be great, the last Tuesday is the 29th, is that good for you?
I need to check with the venue but it should be fine.

**Comment by PureRandom** [comment]
@jamescoward that sounds ok. Ill start getting prepped :)

**Comment by jamescoward** [comment]
@PureRandom awesome! I'll get in touch with the venue today and get back to you. But it should be fine 👍

**Comment by jamescoward** [comment]
hey @PureRandom , spoke with the venue yesterday and we're good to go for the 29th November, I'll make the meetup event today. Would you like me to link to a twitter profile or something else on the event page?

**Comment by PureRandom** [comment]
Hello @jamescoward 

Thank you very much. now the nerves kick in haha

If you would like you can link to my twitter and/or my blog
Blog: http://purerandomcode.wordpress.com
Twitter: https://twitter.com/pateman90

How long should the talk last and is there any guidlines to follow e.g. need to have MK JS tag on every slide, provide the slides after or need to follow a format?

Thank you

**Comment by jamescoward** [comment]
Its a small and friendly crowd :)

We aim for around 20 minutes, but thats not strict at all, shorter or longer is fine as well.
In regards to format there is no guidelines, and the normal format is having the present speak about the topic and then have some time for questions, but again this is up to you really.

There is a projector that takes VGA and HDMI, so if you can bring along a laptop to present off that is great. Otherwise I'll have my macbook so you can send me the slides.

Will you need sound or internet?

**Comment by PureRandom** [comment]
Sounds good, ill try keep it close to the 20 minutes but I can talk :)

Internet will be needed, but I don't need sound.

**Comment by jamescoward** [comment]
Meetup event is up: https://www.meetup.com/mkjscript/events/235001555/

I'll announce it after the meetup next week.

**Comment by jamescoward** [comment]
Hey @PureRandom, just checking up that we're all good for next week.

I'll make sure that there is internet access and I'll be bringing along an HDMI lead. I'll have my laptop top with me so you can present off that if needed.

I'll be arriving at 18.45, and we'll have pizza first and then get started on the talks.

See you next week!

**Comment by PureRandom** [comment]
Hello,

Yer I'm all nervous and ready 😂

Kind Regards,
Christopher Pateman
Pure Random
purerandomcode.wordpress.com

**Comment by jamescoward** [comment]
Hey @PureRandom , thanks for giving this talk, sorry I couldn't make it!
