### ISSUE TITLE
Scalable CSS with ITCSS

### ISSUE THREAD

**Issue by robheritage** [mkjs/talks#15]
This talk will highlight the weaknesses with CSS, some common issues faced by developers working with CSS on growing projects and finally an introduction to ITCSS, an architecture designed to allow CSS to scale!

**Comment by jamescoward** [comment]
Hi @herisites sounds like a great talk!
You want to do it at the next meetup right?

**Comment by robheritage** [comment]
@jamescoward Yeah might as well mate if you haven't already got someone lined up

**Comment by jamescoward** [comment]
Alright awesome. So that'll be the 29th Nov. I'll stick it up on the event page, would you like me to link to your twitter or a bog or something?

Will you need internet for the talk?

**Comment by robheritage** [comment]
Sorry for the late reply mate, I'm useless lol. Twitter is @RobHeritage and I won't really need internet, I'll just have a local slideshow on my laptop. My laptop only has micro HDMI so I'll need to get a HDMI adaptor if there isn't one already?

**Comment by jamescoward** [comment]
No worries!
I'll add your twitter to the event page.
Is it something like this you need? https://www.amazon.co.uk/BlueRigger-Speed-Micro-cable-Ethernet/dp/B0060AU5MW

I will get one for the meetup group, be useful to have.

**Comment by robheritage** [comment]
Yeah that should do the trick. Also, I can't remember off my head but do we just project on to a whiteboard or wall? Is there still something to be able to draw on? If not don't worry I'll just put pictures in my slides.

**Comment by jamescoward** [comment]
We project onto a screen usually, and I believe that there is a whiteboard behind it. I'll checkup and let you know

**Comment by jamescoward** [comment]
Yep there is a whiteboard 👍

**Comment by robheritage** [comment]
Cool, cheers for checking!

**Comment by jamescoward** [comment]
Thanks for speaking @herisites ! Sorry I couldn't make it.
