### ISSUE TITLE
What, Why and How for JavaScript Style Guides

### ISSUE THREAD

**Issue by PureRandom** [mkjs/talks#17]
I will take you on a tour of what a JavaScript Style guide is?, Why you should have one? and How is it best to implement the guide?

I will also show you the guide that has been implemented at my work.

By Chris Pateman 
[@pateman90](https://twitter.com/pateman90)
[Blog](http://purerandomcode.wordpress.com)

**Comment by jamescoward** [comment]
hey @PureRandom, great to see you back for another talk!

Would you like to give this at the meetup in February?

Hopefully I'll be able to make it this time!

**Comment by PureRandom** [comment]
Hello, 

Can do, what date are you thinking? is it Feb Tuesday 28th?

Thanks,

**Comment by PureRandom** [comment]
Hello @jamescoward,

Not sure if you sure my last response?

Do you know the date so I know when to start panicking? :)

Thanks,

**Comment by jamescoward** [comment]
Hey @PureRandom sorry for not getting back to you. I just need to check up a few things and I'll get back to you with the date. Probably will be the 28th, but maybe the 21st.

**Comment by jamescoward** [comment]
@PureRandom date is going to be the 28th 😄

**Comment by jamescoward** [comment]
Hey @PureRandom I've just put the event page up on meetup https://www.meetup.com/mkjscript/events/237681268/

See you in a couple weeks!

**Comment by PureRandom** [comment]
Hey @jamescoward ,

My partner has an appointment 6-7 on the same day as the talk. Hopefully she will finish early so I can get over, but just in case is it possible for my slot to be second or later so I can definitely be there? 

I should 100% be there for about 7:15, which might not be a problem as I know we don't start dead on 7.

Thanks,

**Comment by jamescoward** [comment]
Hey @PureRandom ,

Yeah absolutely no problem. You can take the last slot :)

James

**Comment by PureRandom** [comment]
@jamescoward  that is amazing thank you!

**Comment by jamescoward** [comment]
@PureRandom great talk!!
