### ISSUE TITLE
Serverless Architectures

### ISSUE THREAD

**Issue by alexandercurtis** [mkjs/talks#19]
I could do a talk about my recent experiences with Serverless Architecture, in particular with AWS Lambdas. These are small services, sometimes just a single function, written in Javascript*. I'll cover the why, what and how of Serverless Architecture, with example Lambda code in Javascript, and summarise some of the the pros and cons of this architectural approach.
(* other languages are available).

**Comment by jamescoward** [comment]
hey @alexandercurtis these talk proposals all sound great! 
would you like to give one at the next meetup?

**Comment by alexandercurtis** [comment]
Sure! Probably the serverless one first. Would the meetup be on the last Tuesday in March?

**Comment by jamescoward** [comment]
@alexandercurtis awesome! Yeah it is usually the last Tuesday of the month. Just need to confirm everything and I'll get back to you 👍

**Comment by jamescoward** [comment]
hey @alexandercurtis sorry to take so long to get back to you. We aren't going to be able to run the event on 28th March, so we are planning to have it the week after 4th April. Will that work for you?

**Comment by alexandercurtis** [comment]
@jamescoward No problem, 4th April is fine.

**Comment by jamescoward** [comment]
Hey @alexandercurtis I've scheduled the event here https://www.meetup.com/mkjscript/events/238420714/ 

I've credited your talk to your github, if you want me to change the link to twitter or a blog or something let me know 👍

**Comment by alexandercurtis** [comment]
NP, see you on the 4th

**Comment by alexandercurtis** [comment]
@jamescoward by the way, roughly how long should the talk last?

**Comment by jamescoward** [comment]
We tend to aim for around 20minutes (including Q&A), however if you want to go more or less that, it's absolutely fine. What sort of length were you going to aim for?

**Comment by alexandercurtis** [comment]
I'll aim for 15 minutes plus 5 mins Q&A.

**Comment by jamescoward** [comment]
Perfect 👍

**Comment by jamescoward** [comment]
Hey @alexandercurtis just wanted to check up that everything is good for the event next Tuesday.

Does your laptop have HDMI, or will you need an adaptor?

**Comment by alexandercurtis** [comment]
Yep, all good thanks. I will need an HDMI adapter. I'll try to remember to bring one, but would be good to have a backup!

**Comment by jamescoward** [comment]
What do you need the adaptor from?

**Comment by alexandercurtis** [comment]
Display port

**Comment by jamescoward** [comment]
Like this one https://www.amazon.co.uk/Displayport-Adapter-Benfei-Display-Converter/dp/B017Q8ZVWK/ref=sr_1_3?ie=UTF8&qid=1490868340&sr=8-3&keywords=displayport+to+hdmi

**Comment by alexandercurtis** [comment]
Sorry I mean mini display port. 
https://www.amazon.co.uk/Rankie-DisplayPort-Thunderbolt-Compatible-Adapter/dp/B010SDAXUK/ref=sr_1_2?s=electronics&ie=UTF8&qid=1490872173&sr=1-2&keywords=mini+displayport+to+hdmi

**Comment by jamescoward** [comment]
Ah yeah, cool will have one there just in case 👍
