### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by slyadams** [mkjs/talks#23]
A brief introduction to TypeScript, likely following agenda similar to:

1. Overview and history
2. Typing in JavaScript and how this benefits
3. Compiling and tooling
4. Types for 3rd party libraries
5. Getting started

All of these will hopefully be accompanied by live demos/examples.

**Comment by slyadams** [comment]
Can I just check there will be internet access?

**Comment by jamescoward** [comment]
Yes there is wifi. Sorry for the late reply, just wanted to check it was working properly 😊

**Comment by davidjgoss** [comment]
Great talk @slyadams! I'll leave this issue open, if you post your slides and/or any other resources online, please do link them up from here.

**Comment by slyadams** [comment]
Slides from talk: http://crisp.software/wp-content/uploads/2017/05/TypeScript.pptx
