### ISSUE TITLE
Building the Internet of Things with Node.js

### ISSUE THREAD

**Issue by Louisblack** [mkjs/talks#4]
A practical look at physical programming with a Raspberry Pi and Node.js and how easy it can be to create network connected devices that can interact with the physical world.

I think the talk would be most likely be around 20 minutes especially if I can rustle up a demo.

**Comment by ghost** [comment]
@Louisblack , this sounds really a really cool talk!

Would you be able to do it at the next event on 26th Jan? Or would you like longer to prepare?

**Comment by ghost** [comment]
OK this talk is scheduled for the 26th Jan meetup :grin:
