### ISSUE TITLE
GitEvents - an open source event management platform

### ISSUE THREAD

**Issue by iancrowther** [mkjs/talks#5]
GitEvents is an open source project started as a joint venture between LNUG & BCNJS.

I would like to share with you why the project started, how its progressed and some of the difficulties we have faced growing an OSS project which is still a WIP.  

I'll explain how its architected and how to get involved.

**Comment by ghost** [comment]
Hi @iancrowther do you have an idea of when you would like to do this? We have a meetup coming up on 26th Jan, and then the next one will be a Tuesday towards the end of Feb. We have a new venue a few minutes walk from MK train station so it shouldn't be too difficult for you to get here :)

**Comment by iancrowther** [comment]
Jan is a bit too soon for me, its already pretty hectic :-)
Feb should be ok, I cant do the 2nd or 4th Wednesday of the month.
Can you propose some dates?

**Comment by ghost** [comment]
The Feb event will probably be Tuesday 23rd Feb, would that be OK?

**Comment by iancrowther** [comment]
ah - no can do, I'm a Derby County Season Ticket Holder.. 

23 Feb - Championship
Derby County vs Blackburn - 19:45

How's March looking?

**Comment by ghost** [comment]
Can't miss that!

March will be 22nd or 29th, either of those good?

**Comment by ghost** [comment]
Hi @iancrowther,

Just thought I'd catch up and see if either of those March dates would work for you?
We had the second meet up on Tuesday, with around 25 people attending, hopefully ~30 by March!

**Comment by iancrowther** [comment]
yay - thats fantastic.  

29th is best but both work right now

**Comment by ghost** [comment]
29th works best for me as well. Is it alright if I schedule it in for then?

**Comment by iancrowther** [comment]
Awesome, looking forward to it

**Comment by ghost** [comment]
Great! I'm looking forward to it as well. Where I am hosting the event is very close to the station in MK (a couple minutes walk). I'll get back to you closer to the time with all the details :+1:
