### ISSUE TITLE
Component based UI 2.0

### ISSUE THREAD

**Issue by Qazzian** [mkjs/talks#7]
Building on James's talk in the second meetup, I thought we could talk about the bleeding edge of Component based frameworks for client side javascript development.

Will look at 
- babel.js which translates ES6 into legacy js
- System.js which enables require.js like functionality but with multiple module formats 
- jspm which is npm for the frontend.

**Comment by ghost** [comment]
@Qazzian I'd be really interested in hearing this talk! Do you have an idea when you'd like to give it? The  next meet ups should be 23rd Feb and 22nd/29th March.

**Comment by jamescoward** [comment]
hi @Qazzian, haven't see you at a meetup lately 🙁  are you still interested in giving a talk some time? Else I will close the issue.
