### ISSUE TITLE
Your code sucks (or at least it might)

### ISSUE THREAD

**Issue by Louisblack** [mkjs/talks#9]
In this talk we look at metrics for measuring code quality. With that you can tell if your code sucks or not. We'll also look at how tools can make use of these metrics and analyse your code to track quality over time and ensure it meets a minimum quality standard.

**Comment by ghost** [comment]
@Louisblack I love the title! This sounds like it will be great. Do you have any idea when you would like to do it? So far we have dates lined up 23rd Feb and 29th Mar. Further ahead it will be aiming for the last Tuesday in the month.

**Comment by Louisblack** [comment]
Hey @jrcoward. I have a friend's wedding on the 29th March. If you need another for the 23rd Feb and you don't mind me doing two in a row then I can do that. If you get someone else you wants a chance then I'm happy to do it in April.

**Comment by ghost** [comment]
@Louisblack  If you're happy to do it in Feb that would help me out, means we have two people talking and I can have a bit of breathing room for find more :grin:

**Comment by Louisblack** [comment]
Ok cool. I'll do it on the 23rd... Better start planning then.
